#
# Haiku buildmaster
#
# Runs buildmasters which connect to various builders
# at various remote locations over ssh with verifie
# host keys.
#
# TODO: buildmaster-packages-pvc is a strain on our
# infrastructure. We really need to get it to
# S3,Storj,etc "somehow". Given the difficulty of RWX
# mixed with the size of these volumes, all of these
# have to run on the same node reducing redundancy.
#
# We choose do-block-storage-retain as a storage class
# to "retain" PV's if this deployment is accidently
# deleted. In theory we could create a volume snapshot
# of the unattached volume and restore it to a new
# PVC via kubernetes.

## Teleport doesn't seem used lol
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: teleport
#  labels:
#    app: teleport
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: teleport
#  template:
#    metadata:
#      labels:
#        app: teleport
#    spec:
#      containers:
#      - name: teleport
#        image: mmlr/teleport
#        command: ["./teleport"]
#        args: ["server", "5825", "/run/secrets/auth.db"]
#        volumeMounts:
#        - name: teleport-db
#          readOnly: true
#          mountPath: /run/secrets
#      volumes:
#        - name: teleport-db
#          secret:
#            secretName: teleport-db
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: worker-teleport
#spec:
#  selector:
#    app: teleport
#  ports:
#  - name: teleport 
#    port: 5825
#    targetPort: 5825
#  - name: mmlr-x86-64
#    port: 5001
#    targetPort: 5001
#  - name: mmlr-x86-gcc2
#    port: 5000
#    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haikuporter
  labels:
    app: haikuporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haikuporter
  template:
    metadata:
      labels:
        app: haikuporter
    spec:
      containers:
      - name: buildmaster-frontend
        image: docker.io/haikuporter/buildmaster-frontend:1.2.7-2
        volumeMounts:
        - name: buildmaster-data-x86-gcc2
          mountPath: /var/instances/master/x86_gcc2
        - name: buildmaster-data-x86-64
          mountPath: /var/instances/master/x86_64
        - name: buildmaster-packages
          mountPath: /var/instances/haikuports
      - name: buildmaster-x86-64
        image: docker.io/haikuporter/buildmaster:1.2.7-2
        #command: ["bootstrap", "x86_64"]
        command: ["loop"]
        volumeMounts:
        - name: buildmaster-packages
          mountPath: /var/packages
        - name: buildmaster-sources
          mountPath: /var/sources
        - name: buildmaster-data-x86-64
          mountPath: /var/buildmaster
        env:
          - name: BUILD_TARGET_ARCH
            value: "x86_64"
          - name: REPOSITORY_TRIGGER_URL
            value: "https://depot.haiku-os.org/__repository/haikuports/source/haikuports_x86_64/import"
      - name: buildmaster-x86-gcc2
        image: docker.io/haikuporter/buildmaster:1.2.7-2
        #command: ["bootstrap", "x86_gcc2", "x86"]
        command: ["loop"]
        volumeMounts:
        - name: buildmaster-sources
          mountPath: /var/sources
        - name: buildmaster-packages
          mountPath: /var/packages
        - name: buildmaster-data-x86-gcc2
          mountPath: /var/buildmaster
        env:
          - name: BUILD_TARGET_ARCH
            value: "x86_gcc2"
          - name: REPOSITORY_TRIGGER_URL
            value: "https://depot.haiku-os.org/__repository/haikuports/source/haikuports_x86_gcc2/import"
      volumes:
        - name: buildmaster-data-x86-64
          persistentVolumeClaim:
            claimName: buildmaster-data-x86-64-pvc
        - name: buildmaster-data-x86-gcc2
          persistentVolumeClaim:
            claimName: buildmaster-data-x86-gcc2-pvc
        - name: buildmaster-packages
          persistentVolumeClaim:
            claimName: buildmaster-packages-pvc
        - name: buildmaster-sources
          persistentVolumeClaim:
            claimName: buildmaster-sources-pvc
---
# state data for builds like logs of buildruns, buildrun id
# tracking, builder connection information.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildmaster-data-x86-64-pvc
spec:
  storageClassName: do-block-storage-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# state data for builds like logs of buildruns, buildrun id
# tracking, builder connection information.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildmaster-data-x86-gcc2-pvc
spec:
  storageClassName: do-block-storage-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# all of the packages for Haikuports
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildmaster-packages-pvc
spec:
  storageClassName: do-block-storage-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# pretty much just Haiku sources at this point
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildmaster-sources-pvc
spec:
  storageClassName: do-block-storage-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
