### HaikuDepotServer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haikudepotserver
  labels:
    app: haikudepotserver
spec:
  replicas: 0
  selector:
    matchLabels:
      app: haikudepotserver
  template:
    metadata:
      labels:
        app: haikudepotserver
    spec:
      containers:
      - name: haikudepotserver
        image: docker.io/haiku/haikudepotserver:1.0.128
        resources:
          limits:
            cpu: "1.0"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        volumeMounts:
        - name: haikudepotserver-data
          mountPath: /secrets
      volumes:
      - name: haikudepotserver-data
        persistentVolumeClaim:
          claimName: haikudepotserver-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: haikudepotserver-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: haikudepotserver
spec:
  selector:
    app: haikudepotserver
  ports:
  - name: web
    port: 80
    targetPort: 80
---
# web frontends for haikudepotserver
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haikudepotserver
  annotations:
#    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: web,webs
spec:
  tls:
  - hosts:
    - depot.haiku-os.org
    secretName: tls-cert-depot
  rules:
  - host: depot.haiku-os.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: haikudepotserver
            port:
              name: web
