# Serves haiku and haikuports repositories
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpkg-haiku
  labels:
    app: hpkg-haiku
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hpkg-haiku
  template:
    metadata:
      labels:
        app: hpkg-haiku
    spec:
      containers:
      - name: hpkgbouncer
        image: haiku/hpkgbouncer:0.3.0
        volumeMounts:
        - name: secrets
          mountPath: "/var/run/secrets"
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: s3-repo
          items:
          - key: s3_endpoint
            path: s3_endpoint
          - key: s3_bucket
            path: s3_bucket
          - key: s3_key
            path: s3_key
          - key: s3_secret
            path: s3_secret
---
apiVersion: v1
kind: Service
metadata:
  name: hpkg-haiku
spec:
  selector:
    app: hpkg-haiku
  ports:
  - name: www
    port: 80
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpkg-haikuports
  labels:
    app: hpkg-haikuports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpkg-haikuports
  template:
    metadata:
      labels:
        app: hpkg-haikuports
    spec:
      # Run on the buildmaster node for shared access to packages pvc
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - buildmaster
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx
        image: docker.io/nginx:stable-alpine
        volumeMounts:
        - name: buildmaster-packages
          mountPath: "/usr/share/nginx/html"
          readOnly: true
      volumes:
        - name: buildmaster-packages
          persistentVolumeClaim:
            claimName: buildmaster-packages-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: hpkg-haikuports
spec:
  selector:
    app: hpkg-haikuports
  ports:
  - name: www
    port: 80
    targetPort: 80
---
# web frontends for package repos
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hpkg
  annotations:
#   cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: web,webs
spec:
#  tls:
#  - hosts:
#    - eu.hpkg.haiku-os.org
#    secretName: tls-cert-eu-hpkg
  rules:
  - host: eu.hpkg.haiku-os.org
    http:
      paths:
      - path: /haiku
        pathType: Prefix
        backend:
          service:
            name: hpkg-haiku
            port:
              name: www
      - path: /haikuports
        pathType: Prefix
        backend:
          service:
            name: hpkg-haikuports
            port:
              name: www
