### Haiku SMTP services
#
apiVersion: v1
kind: Service
metadata:
  name: smtp
spec:
  ports:
  - name: smtp
    port: 25
    protocol: TCP
    targetPort: 25
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: smtp
subsets:
- addresses:
  - ip: 10.133.254.78
  ports:
  - name: smtp
    port: 25
    protocol: TCP
