### Haiku SMTP services
#
apiVersion: v1
kind: Service
metadata:
  name: smtp
spec:
  ports:
  - name: smtp
    port: 25
    protocol: TCP
    targetPort: 25
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: smtp
subsets:
- addresses:
  - ip: 10.133.254.78
  ports:
  - name: smtp
    port: 25
    protocol: TCP
## Inbound mail from users
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp-forwarder
  labels:
    app: smtp-forwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp-forwarder
  template:
    metadata:
      labels:
        app: smtp-forwarder
    spec:
      containers:
      - name: smtp
        image: docker.io/zixia/simple-mail-forwarder:latest
        resources:
          limits:
            cpu: "0.50"
            memory: "256Mi"
          requests:
            cpu: "0.15"
            memory: "128Mi"
        env:
        - name: SMF_CONFIG
          value: contact@haiku-inc.org:haiku.inc@gmail.com;donations@haiku-os.org:haiku.inc@gmail.com;contact@haiku-os.org:waddlesplash@gmail.com|kallisti5@unixzen.com;haikustore@haiku-os.org:haiku.inc@gmail.com
---
apiVersion: v1
kind: Service
metadata:
  name: smtp-forwarder
spec:
  selector:
    app: smtp-forwarder
  ports:
  - name: smtp
    protocol: TCP
    port: 25
---
apiVersion: traefik.containo.us/v1alpha1
kind: MiddlewareTCP
metadata:
  name: smtp-ingressmiddle
spec:
  inFlightConn:
    amount: 2
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: smtp-ingresstcp
spec:
  entryPoints:
    - smtp
  routes:
  - match: HostSNI(`*`)
    middlewares:
    - name: smtp-ingressmiddle
    services:
    - name: smtp-forwarder
      port: 25
      weight: 10
      terminationDelay: 400
      proxyProtocol:
        version: 1
