### Haiku Trac
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trac
  labels:
    app: trac
spec:
  replicas: 0
  selector:
    matchLabels:
      app: trac
  template:
    metadata:
      labels:
        app: trac
    spec:
      containers:
      - name: trac
        image: docker.io/haiku/trac:1.4.3-pypy
        resources:
          limits:
            cpu: "2.0"
            memory: "2Gi"
          requests:
            cpu: "0.15"
            memory: "512Mi"
        volumeMounts:
        - name: trac-data
          mountPath: /var/trac
      volumes:
      - name: trac-data
        persistentVolumeClaim:
          claimName: trac-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trac-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: trac
spec:
  selector:
    app: trac
  ports:
  - name: web 
    port: 80 
    targetPort: 80
---
# web frontends for trac
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trac-web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: web,webs
spec:
  tls:
  - secretName: tls-cert-trac
  rules:
  - host: dev.haiku-os.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: trac
            port:
              name: web
