#
# Haiku's continious integration
#
# Description:
#   These containers manage builds of various components of Haiku such as package
#   repositories, nightly os images, release os images, and haikuports builds.
#
version: "3.2"
services:
  www:
    image: dragas/thttpd
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
    networks:
      - ingress_ci
    volumes:
      - ./data/static-html/build:/var/www/http:z
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ingress_ci"
      - "traefik.basic.frontend.rule=Host:build.${DOMAIN}"
      - "traefik.basic.port=80"
  buildbot:
    image: haiku/buildbot-master
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G
    depends_on:
      - postgres
    hostname: buildbot
    volumes:
      - buildbot_config:/var/lib/buildbot:z
      - ./data/buildbot/master.cfg:/var/lib/buildbot/master.cfg:z
    networks:
      - ingress_ci
      - support_default
    ports:
      - 9989:9989
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ingress_ci"
      - "traefik.basic.frontend.rule=Host:build.${DOMAIN};PathPrefixStrip:/buildbot/"
      - "traefik.basic.port=80"
  buildmaster_master_x86_64:
    image: haikuports/buildmaster
    deploy:
      placement:
        constraints: [node.labels.build == true ]
    command: loop
    networks:
      - private
    volumes:
      - sources:/var/sources:z
      - data_master_x86_64:/var/buildmaster:z
      - packages:/var/packages:z
    environment:
      REPOSITORY_TRIGGER_URL: "https://depot.haiku-os.org/__repository/haikuports/source/haikuports_x86_64/import"
  buildmaster_master_x86_gcc2:
    image: haikuports/buildmaster
    deploy:
      placement:
        constraints: [node.labels.build == true ]
    command: loop
    networks:
      - private
    volumes:
      - sources:/var/sources:z
      - data_master_x86_gcc2:/var/buildmaster:z
      - packages:/var/packages:z
    environment:
      REPOSITORY_TRIGGER_URL: "https://depot.haiku-os.org/__repository/haikuports/source/haikuports_x86_gcc2/import"
  buildmaster_teleport:
    image: mmlr/teleport
    command: server 5825 auth.db
    networks:
      - private
    ports:
      - "0.0.0.0:5825:5825"
    volumes:
      - teleport:/var/teleport
  buildmaster_frontend:
    image: haikuports/buildmaster-frontend
    deploy:
      placement:
        constraints: [node.labels.build == true ]
    networks:
      - ingress_ci
      - private
    volumes:
      - sources:/var/sources:ro
      - data_master_x86_gcc2:/var/instances/master/x86_gcc2:ro
      - data_master_x86_64:/var/instances/master/x86_64:ro
      - packages:/var/instances/haikuports:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ingress_ci"
      - "traefik.basic.frontend.rule=Host:build.${DOMAIN};PathPrefixStrip:/buildmaster/"
      - "traefik.basic.port=80"
volumes:
  buildbot_config:
  teleport:
  sources:
  packages:
    driver: rexray/dobs
    driver_opts:
      size: 200
  data_master_x86_gcc2:
  data_master_x86_64:
networks:
  private:
    driver: overlay
  support_default:
    external: true
  ingress_ci:
    external: true
