version: "2.1"
services:
  traefik:
    # Traefik connects to docker and reads labels to form routes
    # Traefik also handles letsencrypt renewals
    image: traefik:latest
    restart: always
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./data/traefik/traefik.toml:/traefik.toml:z
      - traefik_acme:/acme:z
  gerrit:
    # Disable in test environments
    ports:
      - "94.130.158.38:22:29418" # PROD-ONLY
    image: haiku/gerrit
    volumes:
      - gerrit_data:/var/gerrit/review_site:z
      - ./data/gerrit/hooks:/var/gerrit/review_site/hooks:z
    restart: on-failure
    environment:
      - AUTH_TYPE=OAUTH
      - GITWEB_TYPE=cgit
      - JAVA_HEAPLIMIT=1024m
      #- OAUTH_GITHUB_CLIENT_ID=XXXONBOOTSTRAPXXX
      #- OAUTH_GITHUB_CLIENT_SECRET=XXXONBOOTSTRAPXX
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:review${DOMAIN_POST}.haiku-os.org"
      - "traefik.basic.port=8080"
  cgit:
    image: haiku/cgit
    restart: on-failure
    volumes:
      - gerrit_data:/var/git
    environment:
      CGIT_TITLE: "Haiku's repositories"
      CGIT_DESC: 'Presented by cgit on Docker'
      # check section-from-path in cgit docs
      CGIT_VROOT: '/'
      CGIT_SECTION_FROM_STARTPATH: 1
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:cgit${DOMAIN_POST}.haiku-os.org,git${DOMAIN_POST}.haiku-os.org"
      - "traefik.basic.frontend.redirect.regex=cgit${DOMAIN_POST}.haiku-os.org/(.*)"
      - "traefik.basic.frontend.redirect.replacement=git${DOMAIN_POST}.haiku-os.org/$$1"
      - "traefik.basic.port=80"
  irker:
    image: haiku/irker
    restart: on-failure
  pootle:
    image: haiku/pootle
    restart: on-failure
    volumes:
      - pootle_data:/var/pootle:z
    depends_on:
      - postgres
      - redis
      - smtp
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:i18n${DOMAIN_POST}.haiku-os.org;PathPrefixStrip:/pootle/"
      - "traefik.basic.port=80"
  portsmirror:
    image: haiku/ports-mirror
    restart: on-failure
    volumes:
      - ports_mirror:/ports-mirror
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:ports-mirror${DOMAIN_POST}.haiku-os.org"
      - "traefik.basic.port=80"
  postgres:
    image: postgres:9.6
    restart: on-failure
    environment:
      POSTGRES_USER: "baron"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis:4.0
    command: redis-server --appendonly yes
    restart: on-failure
    volumes:
      - redis_data:/data:z
  smtp:
    image: mwader/postfix-relay
    restart: on-failure
    environment:
      - POSTFIX_myhostname=maui.haiku-os.org
  trac:
    image: haiku/trac
    restart: on-failure
    volumes:
      - trac_data:/var/trac:z
    depends_on:
      - postgres
      - smtp
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:dev${DOMAIN_POST}.haiku-os.org"
      - "traefik.basic.port=80"
  userguide:
    image: haiku/userguide
    restart: on-failure
    volumes:
      - userguide_data:/var/userguide:z
    depends_on:
      - postgres
      - smtp
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:i18n${DOMAIN_POST}.haiku-os.org;PathPrefixStrip:/userguide/"
      - "traefik.basic.port=80"
  www-i18n:
    image: dragas/thttpd
    restart: on-failure
    volumes:
      - ./data/static-html/i18n:/var/www/http:z
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:i18n${DOMAIN_POST}.haiku-os.org"
      # redirect /pootle & /userguide to forward to proper containers
      - "traefik.basic.frontend.redirect.regex=i18n${DOMAIN_POST}.haiku-os.org/(pootle|userguide)$$"
      - "traefik.basic.frontend.redirect.replacement=i18n${DOMAIN_POST}.haiku-os.org/$$1/"
      - "traefik.basic.port=80"
  www-build:
    image: dragas/thttpd
    restart: on-failure
    volumes:
      - ./data/static-html/build:/var/www/http:z
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:build${DOMAIN_POST}.haiku-os.org"
      - "traefik.basic.port=80"
  buildbot:
    image: buildbot/buildbot-master:v1.2.0
    hostname: buildbot
    restart: on-failure
    volumes:
      - buildbot_config:/var/lib/buildbot:z
      - ./data/buildbot/master.cfg:/var/lib/buildbot/master.cfg:z
      - nightly_data:/nightly-data:z
      - repo_data:/repo-data:z
    ports:
      - 9989:9989
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:build${DOMAIN_POST}.haiku-os.org;PathPrefixStrip:/buildbot/"
      - "traefik.basic.port=80"
#  cdn:
#    image: haiku/cdn
#    restart: on-failure
#    volumes:
#      - repo_data:/repo-data:z
#      - nightly_data:/nightly-data:z
#      - ./data/cdn/rsync-whitelist:/etc/rsync-whitelist:ro
#    ports:
#      - '0.0.0.0:12000:12000'
volumes:
  traefik_acme:
  buildbot_config:
  gerrit_data:
  pootle_data:
  ports_mirror:
  postgres_data:
  userguide_data:
  trac_data:
  repo_data:
  nightly_data:
  redis_data:
