version: "2.1"
services:
  traefik:
    # Traefik connects to docker and reads labels to form routes
    # Traefik also handles letsencrypt renewals
    image: traefik:1.5.4
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/traefik/traefik.toml:/traefik.toml
      - traefik_acme:/acme
  #router:
  #  image: haiku/nginx-router
  #  ports:
  #    - "0.0.0.0:443:443"
  #    - "0.0.0.0:80:80"
  #  volumes:
  #    - ./data/router:/etc/nginx/conf.d:z
  #    - /etc/letsencrypt:/etc/letsencrypt:z
  #    - ./data/static-html:/static-html:z
  #    - ports_mirror:/ports-mirror:z
  #    - download_data:/download-data:z
  #    - repo_data:/repo-data:z
  #  restart: on-failure
  #  depends_on:
  #    - gerrit
  #    - cgit
  gerrit:
    # Disable in test environments
    ports:
      - "94.130.158.38:22:29418" # PROD-ONLY
    image: haiku/gerrit
    volumes:
      - gerrit_data:/var/gerrit/review_site:z
      - ./data/gerrit/hooks:/var/gerrit/review_site/hooks:z
    restart: on-failure
    environment:
      - AUTH_TYPE=OAUTH
      - GITWEB_TYPE=cgit
      - JAVA_HEAPLIMIT=1024m
      #- OAUTH_GITHUB_CLIENT_ID=XXXONBOOTSTRAPXXX
      #- OAUTH_GITHUB_CLIENT_SECRET=XXXONBOOTSTRAPXX
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:review${DOMAIN_POST}.haiku-os.org"
      - "traefik.basic.port=8080"
  cgit:
    image: haiku/cgit
    restart: on-failure
    volumes:
      - gerrit_data:/var/git
    environment:
      CGIT_TITLE: "Haiku's repositories"
      CGIT_DESC: 'Presented by cgit on Docker'
      # check section-from-path in cgit docs
      CGIT_VROOT: '/'
      CGIT_SECTION_FROM_STARTPATH: 1
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:cgit${DOMAIN_POST}.haiku-os.org,git${DOMAIN_POST}.haiku-os.org"
      - "traefik.basic.port=80"
  irker:
    image: haiku/irker
    restart: on-failure
  pootle:
    image: haiku/pootle
    restart: on-failure
    volumes:
      - pootle_data:/var/pootle:z
    depends_on:
      - postgres
      - redis
      - smtp
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=PathPrefix:/pootle;Host:i18n${DOMAIN_POST}.haiku-os.org"
      - "traefik.basic.port=80"
  portsmirror:
    image: haiku/ports-mirror
    restart: on-failure
    volumes:
      - ports_mirror:/ports-mirror
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:ports-mirror${DOMAIN_POST}.haiku-os.org"
      - "traefik.basic.port=80"
  postgres:
    image: postgres:9.6
    restart: on-failure
    environment:
      POSTGRES_USER: "baron"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis:4.0
    command: redis-server --appendonly yes
    restart: on-failure
    volumes:
      - redis_data:/data:z
  smtp:
    image: mwader/postfix-relay
    restart: on-failure
    environment:
      - POSTFIX_myhostname=maui.haiku-os.org
  trac:
    image: haiku/trac
    restart: on-failure
    volumes:
      - trac_data:/var/trac:z
    depends_on:
      - postgres
      - smtp
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:dev${DOMAIN_POST}.haiku-os.org"
      - "traefik.basic.port=80"
  userguide:
    image: haiku/userguide
    restart: on-failure
    volumes:
      - userguide_data:/var/userguide:z
    depends_on:
      - postgres
      - smtp
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=PathPrefix:/userguide;Host:i18n${DOMAIN_POST}.haiku-os.org"
      - "traefik.basic.port=80"
  buildbot:
    image: buildbot/buildbot-master:v1.1.2
    hostname: buildbot
    restart: on-failure
    volumes:
      - buildbot_config:/var/lib/buildbot:z
      - ./data/buildbot/master.cfg:/var/lib/buildbot/master.cfg:z
    ports:
      - 9989:9989
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=PathPrefix:/buildbot;Host:build${DOMAIN_POST}.haiku-os.org"
      - "traefik.basic.port=80"
#  cdn:
#    image: haiku/cdn
#    restart: on-failure
#    volumes:
#      - repo_data:/repo-data:z
#      - ./data/cdn/rsync-whitelist:/etc/rsync-whitelist:ro
#    ports:
#      - '0.0.0.0:12000:12000'
volumes:
  traefik_acme:
  buildbot_config:
  gerrit_data:
  pootle_data:
  ports_mirror:
  postgres_data:
  userguide_data:
  trac_data:
  download_data:
  repo_data:
  redis_data:
