#
# Haiku's ingress
#
# Description:
#   All inbound http/https traffic flows through here into the destination containers.
#   Traefik routes data to destination containers by polling docker for labels on each
#   container about what should be exposed where.
#   All http/https traffic should flow through here!
#
#   Since the ingress is critical to service "all requests", we run 2 of them and roll
#   updates across one replica at a time.
#
version: "3.2"
services:
  admin:
    image: alpine:latest
    command: "sleep 86400"
    networks:
      - ci
      - core
      - cdn
      - sysadmin
  etcd:
    image: quay.io/coreos/etcd:latest
    command: "etcd"
    environment:
      - ETCD_ADVERTISE_CLIENT_URLS=http://ingress_etcd:2379
      - ETCD_NAME=ingress_etcd.1
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      #- ETCD_INITIAL_CLUSTER=http://ingress_etcd.1:2380
      #- ETCD_INITIAL_CLUSTER_STATE=new
      #- ETCD_INITIAL_CLUSTER_TOKEN=ingress-cluster-1
    deploy:
      replicas: 1
      placement:
        constraints: [node.role==manager]
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - sysadmin
  traefik_bootstrap:
    image: traefik:latest
    command: traefik storeconfig -c/traefik.toml
  traefik:
    # Traefik connects to docker and reads labels to form routes
    # Traefik also handles letsencrypt renewals
    image: traefik:latest
    command: traefik storeconfig -c/traefik.toml
    deploy:
      replicas: 2
      placement:
        constraints: [node.role==manager]
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
    networks:
      - default
      - ci
      - core
      - cdn
      - sysadmin
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:9191:9191"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./data/traefik/traefik.toml:/traefik.toml:z
      - traefik_acme:/acme:z
      - /var/log/traefik:/logs:z
volumes:
  traefik_acme:
networks:
  core:
    driver: overlay
  cdn:
    driver: overlay
  ci:
    driver: overlay
  sysadmin:
    driver: overlay
    attachable: true
