#
# Haiku sysadmin services
#
# Description:
#   Various tools to monitor our containers and alert us about potential issues.
#
version: "3.2"
services:
  node_exporter:
    image: haiku/node_exporter
    networks:
      - ingress_sysadmin
    volumes:
      - /sys:/host/sys:ro,rslave
      - /proc:/host/proc:ro,rslave
    command: --path.procfs /host/proc --path.sysfs /host/sys
  prometheus:
    image: prom/prometheus
    deploy:
      placement:
        constraints: [node.labels.tier == small ]
    networks:
      - ingress_sysadmin
    volumes:
      - ./data/metrics/prometheus.yml:/etc/prometheus/prometheus.yml:z
      - prometheus_data:/prometheus:z
  grafana:
    image: grafana/grafana
    deploy:
      placement:
        constraints: [node.labels.tier == small ]
    networks:
      - ingress_sysadmin
    environment:
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "smtp:25"
      GF_SMTP_FROM_ADDRESS: "admin@metrics.${DOMAIN}"
      GF_SERVER_ROOT_URL: "https://metrics.${DOMAIN}/grafana/"
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:metrics.${DOMAIN};PathPrefixStrip:/grafana/"
      - "traefik.basic.port=3000"
  fathom:
    image: usefathom/fathom:latest
    deploy:
      placement:
        constraints: [node.labels.tier == small ]
    depends_on:
      - postgres
    networks:
      - ingress_sysadmin
    restart: on-failure
    volumes:
      - fathom_secrets:/var/lib/fathom
    command: /app/fathom --config=/var/lib/fathom/config.env server
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:metrics.${DOMAIN}"
      - "traefik.basic.port=8080"
volumes:
  fathom_secrets:
    driver: rexray/dobs
    driver_opts:
      size: 1
  prometheus_data:
    driver: rexray/dobs
    driver_opts:
      size: 5
  grafana_data:
    driver: rexray/dobs
    driver_opts:
      size: 1
networks:
  ingress_sysadmin:
    external: true
