apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-deployment
  namespace: default
  labels:
    app: git
spec:
  replicas: 2
  selector:
    matchLabels:
      app: git
  template:
    metadata:
      labels:
        app: git
    spec:
      containers:
      - name: gerrit
        image: haiku/gerrit:2.16
        volumeMounts:
        - name: gerrit-data
          mountPath: /var/gerrit/review_site
        env:
          - name: AUTH_TYPE
            value: "OAUTH"
          - name: GITWEB_TYPE
            value: cgit
          - name: JAVA_HEAPLIMIT
            value: "1024m"
          - name: SMTP_SERVER
            value: "smtp"
          - name: SMTP_SERVER_PORT
            value: "25"
          - name: SMTP_FROM
            value: "Gerrit <review@review.haiku-os.org>"
          - name: SMTP_CONNECT_TIMEOUT
            value: "30"
      - name: cgit
        image: haiku/cgit
        env:
          - name: CGIT_TITLE
            value: "Haiku's repositories"
          - name: CGIT_DESC
            value: "Presented by cgit on kubernetes"
          - name: CGIT_VROOT
            value: "/"
          - name: CGIT_SECTION_FROM_STARTPATH
            value: "1"
        volumeMounts:
        - name: gerrit-data
          mountPath: /var/git
      volumes:
      - name: gerrit-data
        persistentVolumeClaim:
          claimName: gerrit-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gerrit-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: do-block-storage-persist
---
apiVersion: v1
kind: Service
metadata:
  name: cgit
  namespace: default
spec:
  selector:
    app: git
  ports:
  - name: web
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: review
  namespace: default
spec:
  selector:
    app: git
  ports:
  - name: web
    port: 80
    targetPort: 8080
  - name: git
    port: 2222
    targetPort: 29418
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: git
  namespace: default
spec:
  rules:
  - host: cgit.haiku-os.org
    http:
      paths:
      - path: /
        backend:
          serviceName: cgit
          servicePort: web
  - host: review.haiku-os.org
    http:
      paths:
      - path: /
        backend:
          serviceName: review 
          servicePort: web
