version: "2"
services:
  app:
    image: haiku/nginx-router
    ports:
      - "0.0.0.0:443:443"
      - "0.0.0.0:80:80"
      - "94.130.158.38:22:2222" # Disable me on non-prod!
    volumes:
      - config:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    restart: on-failure
volumes:
  config:
networks:
  default:
    external:
      name: backend
