version: "2"
services:
  app:
    image: nginx/stable
    ports:
      - "0.0.0.0:443:443"
      - "0.0.0.0:80:80"
    volumes:
      - config:/etc/nginx/conf.d
      - ssl:/etc/ssl
    restart: on-failure
volumes:
  config:
  ssl:
