version: "2"
services:
  app:
    image: nginx
    ports:
      - "0.0.0.0:443:443"
      - "0.0.0.0:80:80"
    volumes:
      - config:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letcencrypt
    restart: on-failure
volumes:
  config:
networks:
  default:
    external:
      name: backend
