---
apiVersion: v1
kind: Pod
metadata:
  name: discourse
spec:
  containers:
  - name: discourse
    image: haiku/discuss
    env:
      - name: LANG
        value: "en_US.UTF-8"
      - name: RAILS_ENV
        value: "production"
      - name: UNICORN_WORKERS
        value: "6"
      - name: UNICORN_SIDEKIQS
        value: "1"
      - name: DOCKER_USE_HOSTNAME
        value: "true"
    volumeMounts:
    - name: discourse-shared
      mountPath: /shared
  volumes:
  - name: discourse-shared
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: discourse
spec:
  selector:
    k8s-app: discourse-ingress-lb
  ports:
  - name: web
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: discourse
spec:
  rules:
  - host: "discuss.haiku-os.org"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: discourse
            port:
              name: www
