---
apiVersion: v1
kind: Pod
metadata:
  name: discourse
  namespace: default
spec:
  containers:
  - name: discourse
    image: haiku/discuss
    env:
      - name: LANG
        value: "en_US.UTF-8"
      - name: RAILS_ENV
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: UNICORN_WORKERS
        value: "6"
      - name: UNICORN_SIDEKIQS
        value: "1"
      - name: DOCKER_USE_HOSTNAME
        value: "true"
    volumeMounts:
    - name: discourse-shared
      mountPath: /shared
  volumes:
  - name: discourse-shared
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: discourse
  namespace: default
spec:
  selector:
    k8s-app: discourse-ingress-lb
  ports:
  - name: web
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: discourse
  namespace: default
spec:
  rules:
  - host: discuss.haiku-os.org
    http:
      paths:
      - path: /
        backend:
          serviceName: discourse
          servicePort: web
