---
- name: Provision Haiku Compute Node
  hosts: compute
  become_method: sudo
  become_user: root
  vars:
    iscsi_target:
  tasks:
  - name: Configure docker CE repo
    shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - name: Install standard software
    yum:
      pkg: ['yum-utils', 'vim', 'docker-ce', 'iscsi-initiator-utils']
  - name: Force systemd to reread configs
    systemd:
      daemon_reload: yes
  - name: Ensure docker is stopped
    systemd:
      name: docker
      state: stopped
  # TODO: Setup storage
  - name: Ensure docker is started
    systemd:
      name: docker
      state: started
      enabled: yes
