---
roles:
  - name: owner
    github:
      teams: ["haiku:infrastructure"]
    local:
      users: ["admin"]
resources:
  - name: pipeline-time-trigger
    type: time
    icon: alarm
    source:
      start: 1:00 AM
      stop: 6:00 AM
      location: America/Chicago
      days: ((days))
  - name: upload-image
    type: s3
    icon: minidisc
    source:
      bucket: haiku-((profile))-test
      access_key_id: ((s3key))
      secret_access_key: ((s3secret))
      endpoint: ((s3endpoint))
      regexp: ((arch))/haiku-((branch))-(.*)-((arch))-.*\.zip
  - name: checksum-image
    type: s3
    icon: shield-lock-outline
    source:
      bucket: haiku-((profile))-test
      access_key_id: ((s3key))
      secret_access_key: ((s3secret))
      endpoint: ((s3endpoint))
      regexp: ((arch))/haiku-((branch))-(.*)-((arch))-.*\.zip\.*.*
  - name: haiku-git
    type: git
    icon: git
    source:
      uri: https://review.haiku-os.org/haiku.git
      branch: ((branch))
# Jobs
jobs:
  - name: image-((branch))-((arch))
    public: true
    plan:
      - get: pipeline-time-trigger
        trigger: true
      - get: haiku-git
        trigger: false
      - task: build ((branch)) anyboot
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: haiku/toolchain-worker-((branch)) }
          inputs:
            - name: haiku-git
          outputs:
            - name: generated.((arch))
          run:
            path: /bin/bash
            args:
              - -c
              - |
                cd generated.((arch))
                TOOLCHAIN_PRIMARY=""
                TOOLCHAIN_SECONDARY=""
                case "((arch))" in
                    "x86_gcc2h")
                        PRI_TRIPLET=$(../haiku-git/build/scripts/find_triplet x86_gcc2)
                        SEC_TRIPLET=$(../haiku-git/build/scripts/find_triplet x86)
                        TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-x86_gcc2/bin/${PRI_TRIPLET}-"
                        TOOLCHAIN_SECONDARY="--cross-tools-prefix /toolchains/cross-tools-x86/bin/${SEC_TRIPLET}-"
                        ;;
                    "x86_64h")
                        PRI_TRIPLET=$(../haiku-git/build/scripts/find_triplet x86_64)
                        SEC_TRIPLET=$(../haiku-git/build/scripts/find_triplet x86)
                        TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-x86_64/bin/${PRI_TRIPLET}-"
                        TOOLCHAIN_SECONDARY="--cross-tools-prefix /toolchains/cross-tools-x86/bin/${SEC_TRIPLET}-"
                        ;;
                    *)
                        PRI_TRIPLET=$(../haiku-git/build/scripts/find_triplet ((arch)))
                        TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-((arch))/bin/${PRI_TRIPLET}-"
                        TOOLCHAIN_SECONDARY=""
                        ;;
                esac
                ../haiku-git/configure $TOOLCHAIN_PRIMARY $TOOLCHAIN_SECONDARY
                jam -j2 -q @((profile))-anyboot
      - task: package ((branch)) anyboot
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: haiku/general-worker }
          inputs:
            - name: haiku-git
            - name: generated.((arch))
          outputs:
            - name: artifacts.((arch))
          run:
            path: /bin/bash
            args:
              - -c
              - |
                RELEASE=$(git -C haiku-git tag -l --points-at HEAD)
                cp generated.((arch))/haiku-((profile))-anyboot.iso artifacts.((arch))/haiku-((branch))-$RELEASE-((arch))-anyboot.iso
                cp haiku-git/ReadMe.md artifacts.((arch))/ReadMe.md
                cd artifacts.((arch))
                zip -9 haiku-((branch))-$RELEASE-((arch))-anyboot.zip ReadMe.md haiku-((branch))-$RELEASE-((arch))-anyboot.iso
                rm *.md
                rm *.iso
                sha256sum --tag haiku-((branch))-$RELEASE-((arch))-anyboot.zip > haiku-((branch))-$RELEASE-((arch))-anyboot.zip.sha256
      - put: upload-image
        params:
          file: artifacts.((arch))/haiku-((branch))-*.zip
      - put: checksum-image
        params:
          file: artifacts.((arch))/haiku-((branch))-*.zip.sha256
  - name: repo-((branch))-((arch))
    public: true
    plan:
      - get: pipeline-time-trigger
        trigger: true
      - get: haiku-git
        trigger: false
      - task: build ((branch)) repository
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: haiku/toolchain-worker-((branch)) }
          inputs:
            - name: haiku-git
          outputs:
            - name: generated.((arch))
          run:
            path: /bin/bash
            args:
              - -c
              - |
                cd generated.((arch))
                TOOLCHAIN_PRIMARY=""
                TOOLCHAIN_SECONDARY=""
                case "((arch))" in
                    "x86_gcc2h")
                        PRI_TRIPLET=$(../haiku-git/build/scripts/find_triplet x86_gcc2)
                        SEC_TRIPLET=$(../haiku-git/build/scripts/find_triplet x86)
                        TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-x86_gcc2/bin/${PRI_TRIPLET}-"
                        TOOLCHAIN_SECONDARY="--cross-tools-prefix /toolchains/cross-tools-x86/bin/${SEC_TRIPLET}-"
                        ;;
                    "x86_64h")
                        PRI_TRIPLET=$(../haiku-git/build/scripts/find_triplet x86_64)
                        SEC_TRIPLET=$(../haiku-git/build/scripts/find_triplet x86)
                        TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-x86_64/bin/${PRI_TRIPLET}-"
                        TOOLCHAIN_SECONDARY="--cross-tools-prefix /toolchains/cross-tools-x86/bin/${SEC_TRIPLET}-"
                        ;;
                    *)
                        PRI_TRIPLET=$(../haiku-git/build/scripts/find_triplet ((arch)))
                        TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-((arch))/bin/${PRI_TRIPLET}-"
                        TOOLCHAIN_SECONDARY=""
                        ;;
                esac
                ../haiku-git/configure $TOOLCHAIN_PRIMARY $TOOLCHAIN_SECONDARY
                jam -q @((profile))-raw build \<repository\>Haiku
      - task: prepare ((branch)) repository
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: haiku/generic-worker }
          inputs:
            - name: haiku-git
            - name: generated.((arch))
          outputs:
            - name: repository.((arch))
          params:
            S3_ENDPOINT: ((s3endpoint))
            S3_SECRET: secretstuff
            S3_KEY: keystuff
          run:
            path: /bin/bash
            args:
              - -c
              - |
                REPODIR="generated.((arch))/objects/haiku/$targetArch/packaging/repositories/Haiku"
                VERSION=$(basename $REPODIR/packages/haiku-*.hpkg | cut -d- -f2)
                TARGET_REPO="repository.((arch))/((arch))/$VERSION"
                mkdir -p $TARGET_REPO
                cp -R $REPODIR $TARGET_REPO
                mc config host add remote $S3_ENDPOINT $S3_KEY $S3_SECRET --api "s3v4"
