---
roles:
  - name: owner
    github:
      teams: ["haiku:infrastructure"]
    local:
      users: ["admin"]
resources:
  - name: haiku-git
    type: git
    icon: git
    source:
      uri: https://review.haiku-os.org/haiku.git
      branch: ((branch))
task-build-image: &task-build-image
  platform: linux
  image_resource:
    type: registry-image
    source: { repository: haiku/toolchain-worker-((branch)) }
  inputs:
    - name: haiku-git
  outputs:
    - name: generated.((arch))
  run:
    path: /bin/bash
    args:
      - -c
      - |
        cd generated.((arch))
        TOOLCHAIN_PRIMARY=""
        TOOLCHAIN_SECONDARY=""
        case "((arch))" in
            "x86_gcc2h")
                PRI_TRIPLET=$(../haiku-git/build/scripts/find_triplet x86_gcc2)
                SEC_TRIPLET=$(../haiku-git/build/scripts/find_triplet x86)
                TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-x86_gcc2/bin/${PRI_TRIPLET}-"
                TOOLCHAIN_SECONDARY="--cross-tools-prefix /toolchains/cross-tools-x86/bin/${SEC_TRIPLET}-"
                ;;
            "x86_64h")
                PRI_TRIPLET=$(../haiku-git/build/scripts/find_triplet x86_64)
                SEC_TRIPLET=$(../haiku-git/build/scripts/find_triplet x86)
                TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-x86_64/bin/${PRI_TRIPLET}-"
                TOOLCHAIN_SECONDARY="--cross-tools-prefix /toolchains/cross-tools-x86/bin/${SEC_TRIPLET}-"
                ;;
            *)
                PRI_TRIPLET=$(../haiku-git/build/scripts/find_triplet ((arch)))
                TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-((arch))/bin/${PRI_TRIPLET}-"
                TOOLCHAIN_SECONDARY=""
                ;;
        esac
        ../haiku-git/configure $TOOLCHAIN_PRIMARY $TOOLCHAIN_SECONDARY
        jam -q @((profile))-((type))

# Jobs
jobs:
  - name: haiku-((branch))-((arch))
    public: true
    plan:
      - get: haiku-git
        trigger: true
      - task: build ((branch)) @((profile))-((type))
        config:
          << : *task-build-image
