---

resource_types:
  - name: irc-notification
    type: docker-image
    source:
      repository: flavorjones/irc-notification-resource
resources:
#  - name: haiku-irc
#    type: irc-notification
#    icon: bullhorn
#    source:
#      server: irc.freenode.net
#      port: 6667
#      channel: "#haiku"
#      join: true
#      user: haiku-ci-bot
#      password: thisisastupidfield
#      usetls: false
  - name: nightly-s3
    type: s3
    bucket: haiku-nightly
    access_key_id: ((s3key))
    secret_access_key: ((s3secret))
    endpoint: https://s3.wasabisys.com
  - name: haiku-git
    type: git
    icon: git
    source:
      uri: https://review.haiku-os.org/haiku.git
      branch: ((branch))

task-build-anyboot: &task-build-anyboot
  platform: linux
  image_resource:
    type: registry-image
    source: { repository: haiku/toolchain-worker }
  inputs:
    - name: haiku-git
  run:
    path: /bin/bash
    args:
      - -c
      - |
        cd generated.((arch))
        ../haiku-git/configure --cross-tools-prefix /toolchains/bin/((arch))-unknown-haiku-
        jam -q @((profile))-anyboot
  outputs:
    - name: generated.((arch))

# Jobs
jobs:
  - name: haiku-((branch))-((arch))
    public: true
    plan:
      - get: haiku-git
        trigger: true
      - task: build ((branch)) anyboot
        config:
          << : *task-build-anyboot
