---
roles:
  - name: owner
    github:
      teams: ["haiku:infrastructure"]
    local:
      users: ["admin"]
resources:
  - name: haiku-git
    type: git
    icon: git
    source:
      uri: https://review.haiku-os.org/haiku.git
      branch: ((branch))
task-build-image: &task-build-image
  platform: linux
  image_resource:
    type: registry-image
    source: { repository: haiku/toolchain-worker-((branch)) }
  inputs:
    - name: haiku-git
  outputs:
    - name: generated.((arch))
  run:
    path: /bin/bash
    args:
      - -c
      - |
        cd generated.((arch))
        TOOLCHAIN_PRIMARY=""
        TOOLCHAIN_SECONDARY=""
        case "((arch))" in
            "ppc")
                TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-((arch))/bin/powerpc-apple-haiku-"
                TOOLCHAIN_SECONDARY=""
                ;;
            "sparc")
                TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-((arch))/bin/sparc64-unknown-haiku-"
                TOOLCHAIN_SECONDARY=""
                ;;
            "x86_gcc2" | "x86")
                TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-((arch))/bin/i586-pc-haiku-"
                TOOLCHAIN_SECONDARY=""
                ;;
            "x86_gcc2h")
                TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-x86_gcc2/bin/i586-pc-haiku-"
                TOOLCHAIN_SECONDARY="--cross-tools-prefix /toolchains/cross-tools-x86/bin/i586-pc-haiku-"
                ;;
            "x86_64h")
                TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-x86_64/bin/x86_64-unknown-haiku-"
                TOOLCHAIN_SECONDARY="--cross-tools-prefix /toolchains/cross-tools-x86/bin/i586-pc-haiku-"
                ;;
            *)
                TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-((arch))/bin/((arch))-unknown-haiku-"
                TOOLCHAIN_SECONDARY=""
                ;;
        esac
        ../haiku-git/configure $TOOLCHAIN_PRIMARY $TOOLCHAIN_SECONDARY
        jam -q @((profile))-((type))

# Jobs
jobs:
  - name: haiku-((branch))-((arch))
    public: true
    plan:
      - get: haiku-git
        trigger: true
      - task: build ((branch)) @((profile))-((type))
        config:
          << : *task-build-image
