---
roles:
  - name: owner
    github:
      teams: ["haiku:infrastructure"]
    local:
      users: ["admin"]
resource_types:
  - name: irc-notification
    type: docker-image
    source:
      repository: flavorjones/irc-notification-resource
resources:
#  - name: haiku-irc
#    type: irc-notification
#    icon: bullhorn
#    source:
#      server: irc.freenode.net
#      port: 6667
#      channel: "#haiku"
#      join: true
#      user: haiku-ci-bot
#      password: thisisastupidfield
#      usetls: false
  - name: upload-image
    type: s3
    icon: minidisc
    source:
      bucket: haiku-((profile))-test
      access_key_id: ((s3key))
      secret_access_key: ((s3secret))
      endpoint: ((s3endpoint))
      regexp: ((arch))/haiku-((branch))-(.*)-((arch))-.*\.zip
  - name: checksum-image
    type: s3
    icon: shield-lock-outline
    source:
      bucket: haiku-((profile))-test
      access_key_id: ((s3key))
      secret_access_key: ((s3secret))
      endpoint: ((s3endpoint))
      regexp: ((arch))/haiku-((branch))-(.*)-((arch))-.*\.zip\.*.*
  - name: upload-repo
    type: s3
    icon: package
    source:
      bucket: haiku-repositories-test
      access_key_id: ((s3key))
      secret_access_key: ((s3secret))
      endpoint: ((s3endpoint))
      regexp: ((arch))/(.*)
  - name: haiku-git
    type: git
    icon: git
    source:
      uri: https://review.haiku-os.org/haiku.git
      branch: ((branch))
# Jobs
jobs:
  - name: image-((branch))-((arch))
    public: true
    plan:
      - get: haiku-git
        trigger: false
      - task: build ((branch)) anyboot
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: haiku/toolchain-worker-((branch)) }
          inputs:
            - name: haiku-git
          outputs:
            - name: generated.((arch))
          run:
            path: /bin/bash
            args:
              - -c
              - |
                cd generated.((arch))
                TOOLCHAIN_PRIMARY=""
                TOOLCHAIN_SECONDARY=""
                case "((arch))" in
                    "ppc")
                        TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-((arch))/bin/powerpc-apple-haiku-"
                        TOOLCHAIN_SECONDARY=""
                        ;;
                    "sparc")
                        TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-((arch))/bin/sparc64-unknown-haiku-"
                        TOOLCHAIN_SECONDARY=""
                        ;;
                    "x86_gcc2" | "x86")
                        TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-((arch))/bin/i586-pc-haiku-"
                        TOOLCHAIN_SECONDARY=""
                        ;;
                    "x86_gcc2h")
                        TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-x86_gcc2/bin/i586-pc-haiku-"
                        TOOLCHAIN_SECONDARY="--cross-tools-prefix /toolchains/cross-tools-x86/bin/i586-pc-haiku-"
                        ;;
                    "x86_64h")
                        TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-x86_64/bin/x86_64-unknown-haiku-"
                        TOOLCHAIN_SECONDARY="--cross-tools-prefix /toolchains/cross-tools-x86/bin/i586-pc-haiku-"
                        ;;
                    *)
                        TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-((arch))/bin/((arch))-unknown-haiku-"
                        TOOLCHAIN_SECONDARY=""
                        ;;
                esac
                ../haiku-git/configure $TOOLCHAIN_PRIMARY $TOOLCHAIN_SECONDARY
                jam -j2 -q @((profile))-anyboot
      - task: package ((branch)) anyboot
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: haiku/general-worker }
          inputs:
            - name: haiku-git
            - name: generated.((arch))
          outputs:
            - name: artifacts.((arch))
          run:
            path: /bin/bash
            args:
              - -c
              - |
                RELEASE=$(git -C haiku-git tag -l --points-at HEAD)
                cp generated.((arch))/haiku-((profile))-anyboot.iso artifacts.((arch))/haiku-((branch))-$RELEASE-((arch))-anyboot.iso
                cp haiku-git/ReadMe.md artifacts.((arch))/ReadMe.md
                cd artifacts.((arch))
                zip -9 haiku-((branch))-$RELEASE-((arch))-anyboot.zip ReadMe.md haiku-((branch))-$RELEASE-((arch))-anyboot.iso
                rm *.md
                rm *.iso
                sha256sum --tag haiku-((branch))-$RELEASE-((arch))-anyboot.zip > haiku-((branch))-$RELEASE-((arch))-anyboot.zip.sha256
      - put: upload-image
        params:
          file: artifacts.((arch))/haiku-((branch))-*.zip
      - put: checksum-image
        params:
          file: artifacts.((arch))/haiku-((branch))-*.zip.sha256
  - name: repo-((branch))-((arch))
    public: true
    plan:
      - get: haiku-git
      - task: build ((branch)) repository
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: haiku/toolchain-worker-((branch)) }
          inputs:
            - name: haiku-git
          outputs:
            - name: generated.((arch))
          run:
            path: /bin/bash
            args:
              - -c
              - |
                cd generated.((arch))
                TOOLCHAIN_PRIMARY=""
                TOOLCHAIN_SECONDARY=""
                case "((arch))" in
                    "ppc")
                        TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-((arch))/bin/powerpc-apple-haiku-"
                        TOOLCHAIN_SECONDARY=""
                        ;;
                    "sparc")
                        TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-((arch))/bin/sparc64-unknown-haiku-"
                        TOOLCHAIN_SECONDARY=""
                        ;;
                    "x86_gcc2" | "x86")
                        TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-((arch))/bin/i586-pc-haiku-"
                        TOOLCHAIN_SECONDARY=""
                        ;;
                    "x86_gcc2h")
                        TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-x86_gcc2/bin/i586-pc-haiku-"
                        TOOLCHAIN_SECONDARY="--cross-tools-prefix /toolchains/cross-tools-x86/bin/i586-pc-haiku-"
                        ;;
                    "x86_64h")
                        TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-x86_64/bin/x86_64-unknown-haiku-"
                        TOOLCHAIN_SECONDARY="--cross-tools-prefix /toolchains/cross-tools-x86/bin/i586-pc-haiku-"
                        ;;
                    *)
                        TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-((arch))/bin/((arch))-unknown-haiku-"
                        TOOLCHAIN_SECONDARY=""
                        ;;
                esac
                ../haiku-git/configure $TOOLCHAIN_PRIMARY $TOOLCHAIN_SECONDARY
                jam -q @((profile))-raw build \<repository\>Haiku
      - task: prepare ((branch)) repository
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: haiku/generic-worker }
          inputs:
            - name: haiku-git
            - name: generated.((arch))
          outputs:
            - name: repository.((arch))
          run:
            path: /bin/bash
            args:
              - -c
              - |
                REPODIR="generated.((arch))/objects/haiku/$targetArch/packaging/repositories/Haiku"
                VERSION=$(basename $REPODIR/packages/haiku-*.hpkg | cut -d- -f2)
                TARGET_REPO="repository.((arch))/((arch))/$VERSION"
                mkdir -p $TARGET_REPO
                cp -R $REPODIR $TARGET_REPO
      - put: upload-repo
        params:
          file: repository.((arch))/((arch))/*
