# A simple Traefik v2.6 ingress controller
# CRD's are for the birds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: docker.io/traefik:v2.6
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: gitssh
          containerPort: 2200
        - name: rsync
          containerPort: 12000
        - name: sftp
          containerPort: 1099
        args:
        - --providers.kubernetesingress=true
        - --providers.kubernetesingress.ingressclass=default
        - --entrypoints.web.address=:80
        - --entrypoints.webs.address=:443
        - --entrypoints.webs.http.tls
        - --entrypoints.gitssh.address=:2200
        - --entrypoints.rsync.address=:12000
        - --entrypoints.sftp.address=:1099
        - --api
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-service
  namespace: kube-system
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
    - protocol: TCP
      port: 22
      name: gitssh
    - protocol: TCP
      port: 12000
      name: rsync
    - protocol: TCP
      port: 1099
      name: sftp
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: default
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: traefik.io/ingress-controller
#---
#apiVersion: cert-manager.io/v1
#kind: ClusterIssuer
#metadata:
#  name: selfsigned
#spec:
#  selfSigned: {}
